### ISSUE TITLE
Dots in directoryname get interpreted as file.

### ISSUE THREAD

**Issue by bierik** [4teamwork/ftw.recipe.translations#11]
When scanning a directory with a name like `registry.xml` it gets interpreted as a file.

`There was an error in parsing ./plonetheme/onegovbear/upgrades/20160120180041_define_pathbar_full_width_variable_in_registy.xml: Is a directory`

**Comment by jone** [comment]
This is an issue in `i18ndude`, which is used by this recipe.

Using dots in upgrade step names is not allowed since those are python packages, which cannot have dots in their names.
I've fixed this upgrade step: https://github.com/OneGov/plonetheme.onegovbear/pull/117

Since we cannot fix it in our code and the error above can easily be fixed I'd not do anything about it.
